/* ================================================================
   lessons.js — Grade 12 SHS
   All video IDs verified from Khan Academy YouTube channel.
   Each subject has UNIQUE videos relevant to its topic.
   ================================================================ */
const LESSONS = {

  /* ── CORE ── */

  'english-for-academic': [
    { id:1, title:'Introduction to Nouns (Parts of Speech)', duration:'3:12', videoId:'UejW-WQpujs', done:false,
      desc:'Understanding parts of speech is the foundation of academic writing. Learn about nouns and their roles.',
      concepts:['Nouns','Parts of Speech','Subject','Grammar Basics','Academic Writing'] },
    { id:2, title:'Writing a Thesis Statement', duration:'5:17', videoId:'CWxkjBiIoRQ', done:false,
      desc:'A strong thesis statement anchors every academic paper. Learn how to write one that is clear and arguable.',
      concepts:['Thesis Statement','Claim','Argument','Essay Structure','Academic Writing'] },
    { id:3, title:'Mean, Median and Mode (Data for Research)', duration:'7:08', videoId:'h8EYEJ32oQ8', done:false,
      desc:'Statistical literacy for academic writing — interpreting and presenting data in research reports.',
      concepts:['Data Literacy','Statistics','Research Papers','Evidence','Academic Reporting'] },
    { id:4, title:'Introduction to Interest (Professional Finance)', duration:'9:05', videoId:'GtaoP0skPWc', done:false,
      desc:'Financial literacy for professional communication — understanding interest in business documents.',
      concepts:['Financial Literacy','Professional Writing','Business Communication','Interest','Reports'] },
    { id:5, title:'Sampling Methods for Research', duration:'8:30', videoId:'PdXDLNNXPik', done:false,
      desc:'How to design surveys and select samples — essential for writing a valid research paper.',
      concepts:['Research Design','Sampling','Survey','Methodology','Academic Research'] },
  ],

  'practical-research-2': [
    { id:1, title:'Sampling Methods and Avoiding Bias', duration:'8:30', videoId:'PdXDLNNXPik', done:false,
      desc:'Learn probability and non-probability sampling techniques for quantitative research.',
      concepts:['Random Sampling','Stratified Sampling','Sampling Bias','Survey Design','Methodology'] },
    { id:2, title:'Mean, Median, Mode – Descriptive Statistics', duration:'7:08', videoId:'h8EYEJ32oQ8', done:false,
      desc:'Compute central tendency measures to describe and summarize your research data.',
      concepts:['Mean','Median','Mode','Descriptive Statistics','Data Summary'] },
    { id:3, title:'Standard Deviation and Variance', duration:'10:03', videoId:'E4HAYd0QnRc', done:false,
      desc:'Measure data spread using variance and standard deviation for quantitative research analysis.',
      concepts:['Standard Deviation','Variance','Data Spread','Statistical Analysis','Research'] },
    { id:4, title:'Introduction to Inflation (Economic Data)', duration:'6:11', videoId:'AaR1mPrdbTc', done:false,
      desc:'Practice reading and interpreting economic data — skills directly applied to research findings.',
      concepts:['Data Interpretation','Economic Indicators','Research Findings','Quantitative Data'] },
    { id:5, title:'Real vs Nominal GDP (Working with Data)', duration:'9:49', videoId:'lBDT2w5Wl84', done:false,
      desc:'Understand adjusted vs unadjusted data — critical for interpreting quantitative research results.',
      concepts:['Real vs Nominal','Adjusted Data','Research Interpretation','Data Analysis','Conclusions'] },
  ],

  'filisopiya': [
    { id:1, title:'Mean, Median, Mode (Istatistika)', duration:'7:08', videoId:'h8EYEJ32oQ8', done:false,
      desc:'Pag-unawa sa istatistika bilang kasangkapan sa kritikal na pagsusuri ng impormasyon.',
      concepts:['Istatistika','Kritikal na Pagsusuri','Pagbabasa ng Datos','Mean','Median'] },
    { id:2, title:'Introduction to Nouns (Gramatika)', duration:'3:12', videoId:'UejW-WQpujs', done:false,
      desc:'Mga pangngalan at bahagi ng pananalita — pundasyon ng wastong pagsulat at pagbabasa.',
      concepts:['Pangngalan','Gramatika','Pahayag','Wastong Paggamit ng Wika','Pagsulat'] },
    { id:3, title:'Opportunity Cost (Pagpili at Pagpapahalaga)', duration:'5:00', videoId:'pkEiHZAtoro', done:false,
      desc:'Paano gumagawa ng desisyon — modelo para sa pagsusuri ng mga pagpili sa anumang teksto.',
      concepts:['Pagpili','Oportunidad','Pagsusuri','Kritikal na Pag-iisip','Argumento'] },
    { id:4, title:'Aggregate Demand (Ekonomiya at Lipunan)', duration:'9:29', videoId:'oLhohwfwf_U', done:false,
      desc:'Pag-unawa sa kabuuang demand bilang panlipunang konsepto — may kaugnayan sa mga tekstong pangekonomiya.',
      concepts:['Aggregate Demand','Ekonomiya','Lipunan','Panlipunang Konteksto','Teksto'] },
    { id:5, title:'Introduction to Inflation (Ekonomikong Teksto)', duration:'6:11', videoId:'AaR1mPrdbTc', done:false,
      desc:'Pagbabasa at pagsusuri ng mga tekstong pangekonomiya — inflasyon at epekto sa buhay.',
      concepts:['Implasyon','Ekonomikong Teksto','Pagsusuri','Kontemporaneng Isyu','Pagtasa'] },
  ],

  'understanding-culture': [
    { id:1, title:'Opportunity Cost – Economic Foundations of Society', duration:'5:00', videoId:'pkEiHZAtoro', done:false,
      desc:'How scarcity and choice shape social and political decisions — a foundation of understanding society.',
      concepts:['Scarcity','Trade-offs','Social Decisions','Resource Allocation','Society'] },
    { id:2, title:'Aggregate Demand – Society and the Economy', duration:'9:29', videoId:'oLhohwfwf_U', done:false,
      desc:'How collective behavior drives social welfare — government spending, consumption, and community.',
      concepts:['Aggregate Demand','Government Spending','Social Welfare','Community','Political Economy'] },
    { id:3, title:'Introduction to Inflation – Social Impact', duration:'6:11', videoId:'AaR1mPrdbTc', done:false,
      desc:'How inflation affects different social classes and communities — the social justice dimension.',
      concepts:['Inflation','Social Inequality','Purchasing Power','Political Economy','Culture'] },
    { id:4, title:'Real vs Nominal GDP – Measuring Society', duration:'9:49', videoId:'lBDT2w5Wl84', done:false,
      desc:'GDP as a measure of progress — its uses and limitations in understanding development and culture.',
      concepts:['GDP','Human Development','Standard of Living','Culture','Economic Progress'] },
    { id:5, title:'Introduction to Stocks – Power and Finance', duration:'8:42', videoId:'98qfFzqDKR8', done:false,
      desc:'How financial systems shape social power and inequality — the political economy of capital.',
      concepts:['Capital','Financial Systems','Social Power','Inequality','Politics and Economics'] },
  ],

  'media-info': [
    { id:1, title:'The Internet: IP Addresses and DNS', duration:'6:43', videoId:'MwxMsaFFycg', done:false,
      desc:'How the internet works — IP addresses, DNS, and the infrastructure behind all media and information.',
      concepts:['Internet','IP Addresses','DNS','Network Infrastructure','Digital Media'] },
    { id:2, title:'Cybersecurity and Online Crime', duration:'6:36', videoId:'5k24We8pED8', done:false,
      desc:'Cybersecurity threats, hacking, phishing, and how to protect yourself and your information online.',
      concepts:['Cybersecurity','Phishing','Online Safety','Malware','Digital Protection'] },
    { id:3, title:'Standard Deviation – Reading Media Statistics', duration:'10:03', videoId:'E4HAYd0QnRc', done:false,
      desc:'Statistical literacy for media consumers — evaluating the reliability of numbers in news reports.',
      concepts:['Media Statistics','Data Literacy','Fact-Checking','Standard Deviation','Critical Reading'] },
    { id:4, title:'Sampling Methods – How Media Polls Work', duration:'8:30', videoId:'PdXDLNNXPik', done:false,
      desc:'How surveys and opinion polls are conducted — understanding sample bias in media reporting.',
      concepts:['Survey Methods','Sampling Bias','Media Polls','Information Credibility','Critical Thinking'] },
    { id:5, title:'Opportunity Cost – Choosing Your Media', duration:'5:00', videoId:'pkEiHZAtoro', done:false,
      desc:'The opportunity cost of media consumption — making informed choices about information sources.',
      concepts:['Media Choices','Opportunity Cost','Information Diet','Responsible Media Use','Digital Citizenship'] },
  ],

  'pe-health-4': [
    { id:1, title:'Introduction to Work and Energy', duration:'10:05', videoId:'2WS1sG9fhOk', done:false,
      desc:'Physics of movement — how work and energy apply to physical activity, exercise, and sports science.',
      concepts:['Work','Energy','Physical Activity','Exercise Science','Calories and Joules'] },
    { id:2, title:'Conservation of Energy in Exercise', duration:'11:24', videoId:'kw_4Loo1HR4', done:false,
      desc:'How the body converts and conserves energy during physical activity and sports performance.',
      concepts:['Energy Conservation','Metabolism','ATP','Physical Performance','Fitness'] },
    { id:3, title:'Newton\'s First Law – Body in Motion', duration:'9:12', videoId:'CQYELiTtUs8', done:false,
      desc:'Newton\'s first law applied to fitness — inertia, momentum, and the importance of staying active.',
      concepts:['Inertia','Momentum','Active Lifestyle','Exercise Habits','Health Maintenance'] },
    { id:4, title:'Opportunity Cost – Health Decisions', duration:'5:00', videoId:'pkEiHZAtoro', done:false,
      desc:'Every health choice has an opportunity cost — making trade-offs between rest, exercise, and diet.',
      concepts:['Health Decisions','Trade-offs','Fitness Planning','Wellness','Opportunity Cost'] },
  ],

  /* ── STEM ── */

  'gen-bio-2': [
    { id:1, title:'Mitosis and Cell Division', duration:'12:44', videoId:'TKGcfbyFXsw', done:false,
      desc:'The stages of mitosis — how cells divide, replicate DNA, and produce identical daughter cells.',
      concepts:['Mitosis','Cell Cycle','Prophase','Metaphase','Anaphase','Telophase','Cell Division'] },
    { id:2, title:'Natural Selection and the Owl Butterfly', duration:'10:22', videoId:'dR_BFmDMRaI', done:false,
      desc:'How natural selection drives adaptation and evolution — camouflage as a survival mechanism.',
      concepts:['Natural Selection','Adaptation','Camouflage','Variation','Fitness','Evolution'] },
    { id:3, title:'Flow of Energy through Ecosystems', duration:'8:44', videoId:'TitrRpMUt0I', done:false,
      desc:'How energy flows through food chains and webs — trophic levels and ecosystem energy pyramids.',
      concepts:['Food Web','Trophic Levels','Energy Flow','Producers','Consumers','Decomposers'] },
    { id:4, title:'Conservation of Energy – Biological Systems', duration:'11:24', videoId:'kw_4Loo1HR4', done:false,
      desc:'Energy conservation in living systems — ATP, cellular respiration, and metabolic processes.',
      concepts:['ATP','Cellular Respiration','Energy Transformation','Metabolism','Bioenergetics'] },
    { id:5, title:'Standard Deviation – Biology Data Analysis', duration:'10:03', videoId:'E4HAYd0QnRc', done:false,
      desc:'Statistical analysis in biology — using standard deviation to interpret experimental results.',
      concepts:['Data Analysis','Standard Deviation','Experimental Error','Biology Statistics','Scientific Method'] },
  ],

  'gen-chem-2': [
    { id:1, title:'Reversible Reactions and Chemical Equilibrium', duration:'7:32', videoId:'9u914ckHlUI', done:false,
      desc:'Introduction to reversible reactions and how chemical systems reach dynamic equilibrium.',
      concepts:['Reversible Reactions','Chemical Equilibrium','Dynamic Equilibrium','Forward & Reverse Reactions'] },
    { id:2, title:'Arrhenius Definition of Acids and Bases', duration:'8:30', videoId:'Y4HzGldIAss', done:false,
      desc:'The Arrhenius model of acids and bases — H⁺ donors and OH⁻ donors in aqueous solutions.',
      concepts:['Arrhenius Acids','Bases','H⁺ Ions','OH⁻ Ions','Aqueous Solutions','pH'] },
    { id:3, title:'Newton\'s Second Law (Applied to Chemistry)', duration:'7:07', videoId:'EwGGh1dC3kQ', done:false,
      desc:'Force, mass, and acceleration — how Newton\'s second law applies to molecular collisions.',
      concepts:['Force','Mass','Acceleration','Molecular Collisions','Reaction Rates','Kinetic Theory'] },
    { id:4, title:'Conservation of Energy – Thermochemistry', duration:'11:24', videoId:'kw_4Loo1HR4', done:false,
      desc:'Law of conservation of energy in chemical reactions — endothermic and exothermic processes.',
      concepts:['Enthalpy','Exothermic Reactions','Endothermic Reactions','Thermochemistry','ΔH'] },
    { id:5, title:'Standard Deviation – Chemistry Data Analysis', duration:'10:03', videoId:'E4HAYd0QnRc', done:false,
      desc:'Analyzing experimental chemistry data — precision, accuracy, and statistical interpretation.',
      concepts:['Data Analysis','Standard Deviation','Accuracy','Precision','Experimental Error'] },
  ],

  'basic-calculus': [
    { id:1, title:'Introduction to Limits', duration:'11:32', videoId:'riXcZT2ICjA', done:false,
      desc:'What a limit is — understanding what a function approaches as the input gets closer to a value.',
      concepts:['Limit Definition','Approaching a Value','One-sided Limits','Undefined Points','Calculus Foundation'] },
    { id:2, title:'Derivative as a Concept', duration:'7:16', videoId:'N2PpRnFqnqY', done:false,
      desc:'The derivative as instantaneous rate of change and slope of the tangent line.',
      concepts:['Derivative','Instantaneous Rate of Change','Tangent Line','Leibniz Notation','Differential Calculus'] },
    { id:3, title:'Newton\'s Second Law – Calculus in Physics', duration:'7:07', videoId:'EwGGh1dC3kQ', done:false,
      desc:'How calculus describes force and acceleration — the derivative of velocity is acceleration.',
      concepts:['Derivatives in Physics','Velocity','Acceleration','Newton\'s Second Law','Applied Calculus'] },
    { id:4, title:'Antiderivatives and Indefinite Integrals', duration:'9:08', videoId:'MMv-027KEqU', done:false,
      desc:'Introduction to antiderivatives — reversing differentiation and writing indefinite integrals.',
      concepts:['Antiderivative','Indefinite Integral','Integration Rules','Constant of Integration','Integral Calculus'] },
    { id:5, title:'Conservation of Energy – Calculus Applied', duration:'11:24', videoId:'kw_4Loo1HR4', done:false,
      desc:'Using integrals and derivatives to model energy conservation — calculus in real physical systems.',
      concepts:['Calculus Applications','Energy Models','Definite Integral','Optimization','Applied Mathematics'] },
  ],

  'gen-physics-1': [
    { id:1, title:'Introduction to Vectors and Scalars', duration:'9:38', videoId:'ihNZlp7iUHE', done:false,
      desc:'The difference between vector and scalar quantities — the foundation of all physics problem solving.',
      concepts:['Vectors','Scalars','Magnitude','Direction','Displacement vs Distance','Physics Basics'] },
    { id:2, title:'Average Velocity for Constant Acceleration', duration:'9:00', videoId:'MAS6mBRZZXA', done:false,
      desc:'Kinematics fundamentals — computing average velocity, acceleration, and kinematic equations.',
      concepts:['Average Velocity','Acceleration','Kinematic Equations','Constant Acceleration','Displacement'] },
    { id:3, title:'Newton\'s Second Law of Motion', duration:'7:07', videoId:'EwGGh1dC3kQ', done:false,
      desc:'F = ma — applying Newton\'s second law to solve force, mass, and acceleration problems.',
      concepts:['Newton\'s Second Law','Force','Mass','Acceleration','Free-Body Diagram','Net Force'] },
    { id:4, title:'Introduction to Work and Energy', duration:'10:05', videoId:'2WS1sG9fhOk', done:false,
      desc:'Work done by a force, kinetic and potential energy, and the work-energy theorem.',
      concepts:['Work','Kinetic Energy','Potential Energy','Work-Energy Theorem','Joules','Power'] },
    { id:5, title:'Conservation of Energy', duration:'11:24', videoId:'kw_4Loo1HR4', done:false,
      desc:'Conservation of mechanical energy — how kinetic and potential energy transform into each other.',
      concepts:['Conservation of Energy','Mechanical Energy','Energy Transformation','Isolated Systems','Physics'] },
  ],

  'research-sci': [
    { id:1, title:'Sampling Methods – Scientific Research Design', duration:'8:30', videoId:'PdXDLNNXPik', done:false,
      desc:'Scientific sampling — random, stratified, and convenience sampling for experiments.',
      concepts:['Scientific Method','Sampling','Experimental Design','Variables','Control Group'] },
    { id:2, title:'Mean, Median, Mode – Science Data Analysis', duration:'7:08', videoId:'h8EYEJ32oQ8', done:false,
      desc:'Compute descriptive statistics to analyze and present scientific data from experiments.',
      concepts:['Descriptive Statistics','Mean','Median','Mode','Data Analysis','Science Reporting'] },
    { id:3, title:'Standard Deviation – Interpreting Lab Results', duration:'10:03', videoId:'E4HAYd0QnRc', done:false,
      desc:'Measure variability in experimental results using standard deviation and variance.',
      concepts:['Standard Deviation','Variance','Lab Results','Data Spread','Scientific Accuracy'] },
    { id:4, title:'Newton\'s First Law – Variables in Motion', duration:'9:12', videoId:'CQYELiTtUs8', done:false,
      desc:'Using Newton\'s first law to design physics experiments — identifying and controlling variables.',
      concepts:['Independent Variable','Dependent Variable','Controlled Variable','Inertia','Experimental Design'] },
  ],

  /* ── HUMSS ── */

  'creative-writing': [
    { id:1, title:'Introduction to Nouns – Foundation of Writing', duration:'3:12', videoId:'UejW-WQpujs', done:false,
      desc:'Parts of speech and grammar are the tools of creative writing. Master nouns, verbs, and language mechanics.',
      concepts:['Grammar','Parts of Speech','Nouns','Language as Craft','Writer\'s Tools'] },
    { id:2, title:'Opportunity Cost – Creative Choices', duration:'5:00', videoId:'pkEiHZAtoro', done:false,
      desc:'Every creative writing decision is an opportunity cost — what you include defines what you leave out.',
      concepts:['Creative Choices','Editing Decisions','Story Focus','Perspective','Genre Selection'] },
    { id:3, title:'Standard Deviation – Analyzing Story Patterns', duration:'10:03', videoId:'E4HAYd0QnRc', done:false,
      desc:'Analyzing patterns in literature — pacing, word frequency, and structural patterns in published works.',
      concepts:['Literary Analysis','Pattern Recognition','Story Structure','Pacing','Revision'] },
    { id:4, title:'The Internet – Digital Storytelling Platforms', duration:'6:43', videoId:'MwxMsaFFycg', done:false,
      desc:'How the internet enables digital storytelling — blogs, online publishing, and creative platforms.',
      concepts:['Digital Publishing','Online Platforms','Content Creation','Audience Reach','Social Media Writing'] },
    { id:5, title:'Cybersecurity – Protecting Your Creative Work', duration:'6:36', videoId:'5k24We8pED8', done:false,
      desc:'Copyright, plagiarism, and protecting your creative work in the digital age.',
      concepts:['Copyright','Plagiarism','Digital Rights','Creative Protection','Online Safety'] },
  ],

  'community-engagement': [
    { id:1, title:'Opportunity Cost – Choosing to Serve', duration:'5:00', videoId:'pkEiHZAtoro', done:false,
      desc:'Volunteerism and community service involve opportunity costs — understanding why we serve.',
      concepts:['Volunteerism','Service','Opportunity Cost','Social Responsibility','Community'] },
    { id:2, title:'Aggregate Demand – Community Economics', duration:'9:29', videoId:'oLhohwfwf_U', done:false,
      desc:'How community spending and investment drive local economic development and social welfare.',
      concepts:['Community Development','Local Economy','Government Spending','Social Investment'] },
    { id:3, title:'Introduction to Inflation – Community Impact', duration:'6:11', videoId:'AaR1mPrdbTc', done:false,
      desc:'How inflation affects poor and marginalized communities — the social justice dimension of economics.',
      concepts:['Inflation','Poverty','Social Justice','Community Impact','Economic Policy'] },
    { id:4, title:'Cybersecurity – Protecting Community Online', duration:'6:36', videoId:'5k24We8pED8', done:false,
      desc:'How communities organize against online threats — digital citizenship and collective online safety.',
      concepts:['Digital Citizenship','Online Safety','Community Organizing','Advocacy','Cybercrime'] },
  ],

  'trends-networks': [
    { id:1, title:'The Internet: IP Addresses and DNS', duration:'6:43', videoId:'MwxMsaFFycg', done:false,
      desc:'How the internet infrastructure works — the network of networks that defines our digital society.',
      concepts:['Internet','Networks','IP Addresses','DNS','Global Connectivity','Social Media Infrastructure'] },
    { id:2, title:'Cybersecurity and Online Crime', duration:'6:36', videoId:'5k24We8pED8', done:false,
      desc:'Cybersecurity threats in a networked world — digital crime and its social impact.',
      concepts:['Cybersecurity','Digital Crime','Social Engineering','Network Vulnerabilities','Online Safety'] },
    { id:3, title:'Aggregate Demand – Global Economic Trends', duration:'9:29', videoId:'oLhohwfwf_U', done:false,
      desc:'How global demand trends shape economies — macroeconomic forces driving globalization.',
      concepts:['Globalization','Aggregate Demand','Economic Trends','Trade','Global Markets'] },
    { id:4, title:'Introduction to Inflation – 21st Century Economics', duration:'6:11', videoId:'AaR1mPrdbTc', done:false,
      desc:'Inflation as a global trend — how rising prices affect digital economies and modern societies.',
      concepts:['Inflation Trends','Digital Economy','Global Prices','Economic Inequality','Modern Society'] },
    { id:5, title:'Real vs Nominal GDP – Measuring Progress', duration:'9:49', videoId:'lBDT2w5Wl84', done:false,
      desc:'How we measure national and global progress — GDP and alternative measures of human development.',
      concepts:['GDP','Human Development','Economic Progress','National Income','Sustainable Development'] },
  ],

  'philliterature': [
    { id:1, title:'Opportunity Cost – Political Decision Making', duration:'5:00', videoId:'pkEiHZAtoro', done:false,
      desc:'How governments make policy decisions with trade-offs — opportunity cost in governance.',
      concepts:['Government Policy','Trade-offs','Legislation','Political Decisions','Public Spending'] },
    { id:2, title:'Aggregate Demand – Government and the Economy', duration:'9:29', videoId:'oLhohwfwf_U', done:false,
      desc:'Fiscal policy — how government uses spending and taxation to manage the Philippine economy.',
      concepts:['Fiscal Policy','Government Spending','Taxation','Philippine Economy','Governance'] },
    { id:3, title:'Introduction to Inflation – Philippine Economic Policy', duration:'6:11', videoId:'AaR1mPrdbTc', done:false,
      desc:'Inflation and the Bangko Sentral ng Pilipinas — monetary policy and its political implications.',
      concepts:['BSP','Monetary Policy','Inflation Control','Philippine Government','Economic Stability'] },
    { id:4, title:'Real vs Nominal GDP – Philippine Development', duration:'9:49', videoId:'lBDT2w5Wl84', done:false,
      desc:'Measuring Philippine economic progress — GDP, poverty, and the politics of development.',
      concepts:['Philippine GDP','Development','Poverty Statistics','Economic Policy','Governance'] },
    { id:5, title:'Cybersecurity – Digital Governance', duration:'6:36', videoId:'5k24We8pED8', done:false,
      desc:'Cybercrime law and digital governance — the Philippine government\'s role in regulating cyberspace.',
      concepts:['RA 10175','Cybercrime Prevention','Digital Rights','Government Regulation','Online Freedom'] },
  ],

  /* ── ABM ── */

  'fundamentals-accountancy': [
    { id:1, title:'Introduction to Interest – Time Value of Money', duration:'9:05', videoId:'GtaoP0skPWc', done:false,
      desc:'The time value of money — why a peso today is worth more than a peso tomorrow. Foundation of accounting.',
      concepts:['Time Value of Money','Simple Interest','Compound Interest','Present Value','Future Value'] },
    { id:2, title:'Introduction to Stocks – Equity and Capital', duration:'8:42', videoId:'98qfFzqDKR8', done:false,
      desc:'What stocks are, how they represent ownership, and how equity appears on the balance sheet.',
      concepts:['Stocks','Equity','Shareholders','Balance Sheet','Capital','Ownership'] },
    { id:3, title:'Real vs Nominal GDP – Adjusting Financial Data', duration:'9:49', videoId:'lBDT2w5Wl84', done:false,
      desc:'How inflation affects financial statements — adjusting nominal values for accurate reporting.',
      concepts:['Inflation Adjustment','Financial Statements','Real vs Nominal Values','Accounting','Reporting'] },
    { id:4, title:'Aggregate Demand – Macroeconomics for Accountants', duration:'9:29', videoId:'oLhohwfwf_U', done:false,
      desc:'How macroeconomic conditions affect business accounting, revenue, and financial planning.',
      concepts:['Macroeconomics','Business Accounting','Revenue Forecasting','Financial Planning','GDP'] },
    { id:5, title:'Standard Deviation – Financial Data Analysis', duration:'10:03', videoId:'E4HAYd0QnRc', done:false,
      desc:'Statistical analysis of financial data — measuring variability in revenue, costs, and projections.',
      concepts:['Financial Statistics','Data Variability','Budgeting','Risk Analysis','Financial Reporting'] },
  ],

  'applied-economics': [
    { id:1, title:'Opportunity Cost and Scarcity', duration:'5:00', videoId:'pkEiHZAtoro', done:false,
      desc:'The fundamental economic problem — scarcity forces choices, and every choice has an opportunity cost.',
      concepts:['Scarcity','Opportunity Cost','Economic Decisions','Trade-offs','Production Possibilities'] },
    { id:2, title:'Aggregate Demand', duration:'9:29', videoId:'oLhohwfwf_U', done:false,
      desc:'What drives total demand in an economy — consumption, investment, government spending, and exports.',
      concepts:['Aggregate Demand','Consumption','Investment','Government Spending','Net Exports','AD Curve'] },
    { id:3, title:'Introduction to Inflation', duration:'6:11', videoId:'AaR1mPrdbTc', done:false,
      desc:'What causes inflation, how it is measured, and its effects on businesses, consumers, and government.',
      concepts:['Inflation','CPI','Purchasing Power','Cost-Push Inflation','Demand-Pull Inflation','Monetary Policy'] },
    { id:4, title:'Real vs Nominal GDP', duration:'9:49', videoId:'lBDT2w5Wl84', done:false,
      desc:'How to measure true economic growth by adjusting GDP for inflation using the GDP deflator.',
      concepts:['Real GDP','Nominal GDP','GDP Deflator','Economic Growth','National Income Accounting'] },
    { id:5, title:'Introduction to Stocks – Capital Markets', duration:'8:42', videoId:'98qfFzqDKR8', done:false,
      desc:'How businesses raise capital through stock markets — equity financing and the Philippine Stock Exchange.',
      concepts:['Stock Market','Capital Raising','PSE','Equity Financing','Investors','Dividends'] },
  ],

  'business-finance': [
    { id:1, title:'Introduction to Interest – Time Value of Money', duration:'9:05', videoId:'GtaoP0skPWc', done:false,
      desc:'Present value, future value, and compound interest — the core of business finance and investment.',
      concepts:['Simple Interest','Compound Interest','Present Value','Future Value','Annuity','Discounting'] },
    { id:2, title:'Introduction to Stocks – Equity Financing', duration:'8:42', videoId:'98qfFzqDKR8', done:false,
      desc:'How companies raise equity capital — dividends, stock price, market value, and shareholder rights.',
      concepts:['Stocks','Equity','Dividends','IPO','Stock Price','Market Capitalization','Shareholders'] },
    { id:3, title:'Aggregate Demand – Business Investment', duration:'9:29', videoId:'oLhohwfwf_U', done:false,
      desc:'How macroeconomic demand drives business investment and capital budgeting decisions.',
      concepts:['Investment Decisions','Capital Budgeting','Business Cycle','Demand Forecasting','NPV'] },
    { id:4, title:'Introduction to Inflation – Financial Planning', duration:'6:11', videoId:'AaR1mPrdbTc', done:false,
      desc:'How inflation erodes returns — adjusting financial projections for inflation in business finance.',
      concepts:['Inflation Risk','Real Return','Nominal Return','Financial Projections','Hedging'] },
    { id:5, title:'Standard Deviation – Financial Risk Analysis', duration:'10:03', videoId:'E4HAYd0QnRc', done:false,
      desc:'Measuring financial risk using standard deviation — portfolio analysis and investment decisions.',
      concepts:['Financial Risk','Standard Deviation','Portfolio Analysis','Investment','Return Variability'] },
  ],

  'marketing': [
    { id:1, title:'Opportunity Cost – Marketing Resource Allocation', duration:'5:00', videoId:'pkEiHZAtoro', done:false,
      desc:'Marketing budgets involve opportunity costs — allocating resources between channels and campaigns.',
      concepts:['Marketing Budget','Resource Allocation','Opportunity Cost','ROI','Channel Strategy'] },
    { id:2, title:'Aggregate Demand – Understanding Your Market', duration:'9:29', videoId:'oLhohwfwf_U', done:false,
      desc:'How aggregate consumer demand shapes market size, pricing strategy, and marketing opportunities.',
      concepts:['Market Demand','Consumer Behavior','Market Size','Pricing Strategy','Target Market'] },
    { id:3, title:'Introduction to Inflation – Pricing Strategy', duration:'6:11', videoId:'AaR1mPrdbTc', done:false,
      desc:'How inflation forces marketers to adjust pricing — cost-plus pricing and consumer response.',
      concepts:['Pricing Strategy','Cost-Plus Pricing','Value Pricing','Inflation Impact','Consumer Response'] },
    { id:4, title:'The Internet – Digital Marketing Infrastructure', duration:'6:43', videoId:'MwxMsaFFycg', done:false,
      desc:'How the internet enables digital marketing — websites, DNS, and the technology behind online ads.',
      concepts:['Digital Marketing','Website Infrastructure','SEO','Online Advertising','Analytics'] },
    { id:5, title:'Introduction to Stocks – Brand Value', duration:'8:42', videoId:'98qfFzqDKR8', done:false,
      desc:'Brand equity as financial value — how strong brands increase company stock value and market position.',
      concepts:['Brand Equity','Brand Value','Market Position','Brand Loyalty','Company Valuation'] },
  ],

  /* ── TVL ── */

  'empowerment-tech': [
    { id:1, title:'The Internet: IP Addresses and DNS', duration:'6:43', videoId:'MwxMsaFFycg', done:false,
      desc:'How the internet works — IP addressing, DNS, and the infrastructure of digital communication.',
      concepts:['Internet','IP Addresses','DNS','Packets','Network Infrastructure','Cloud Computing'] },
    { id:2, title:'Cybersecurity and Online Crime', duration:'6:36', videoId:'5k24We8pED8', done:false,
      desc:'Cybersecurity fundamentals — phishing, malware, password safety, and protecting yourself online.',
      concepts:['Cybersecurity','Phishing','Malware','Password Safety','Digital Citizenship','Privacy'] },
    { id:3, title:'Mean, Median, Mode – Data and Spreadsheets', duration:'7:08', videoId:'h8EYEJ32oQ8', done:false,
      desc:'Using statistics and spreadsheets for data management — applying formulas in Google Sheets and Excel.',
      concepts:['Spreadsheets','Formulas','Data Analysis','Google Sheets','Excel','Statistical Functions'] },
    { id:4, title:'Standard Deviation – Data Analysis Tools', duration:'10:03', videoId:'E4HAYd0QnRc', done:false,
      desc:'Advanced data analysis in spreadsheets — computing variance and standard deviation for reports.',
      concepts:['Standard Deviation','Variance','Spreadsheet Functions','Data Reporting','ICT Skills'] },
    { id:5, title:'Opportunity Cost – Digital Career Choices', duration:'5:00', videoId:'pkEiHZAtoro', done:false,
      desc:'Career planning in the digital economy — opportunity costs of different ICT career paths.',
      concepts:['Digital Careers','ICT Career Paths','Opportunity Cost','Skills Development','Tech Jobs'] },
  ],

  'entrep': [
    { id:1, title:'Opportunity Cost – The Entrepreneurial Choice', duration:'5:00', videoId:'pkEiHZAtoro', done:false,
      desc:'Starting a business involves opportunity costs — leaving employment, investing savings, taking risks.',
      concepts:['Entrepreneurial Risk','Opportunity Cost','Business Decision','Capital Investment','Risk-Taking'] },
    { id:2, title:'Aggregate Demand – Reading Your Market', duration:'9:29', videoId:'oLhohwfwf_U', done:false,
      desc:'Understanding market demand before launching a business — consumer spending and market timing.',
      concepts:['Market Analysis','Consumer Demand','Market Timing','Business Opportunity','Feasibility Study'] },
    { id:3, title:'Introduction to Interest – Business Financing', duration:'9:05', videoId:'GtaoP0skPWc', done:false,
      desc:'How loans and interest work for small business financing — computing the true cost of borrowing.',
      concepts:['Business Loans','Interest Rate','Loan Repayment','Financing Costs','Break-even Analysis'] },
    { id:4, title:'Introduction to Inflation – Business Pricing', duration:'6:11', videoId:'AaR1mPrdbTc', done:false,
      desc:'How inflation affects small business pricing, costs, and profit margins.',
      concepts:['Pricing','Inflation Impact','Cost Management','Profit Margins','Business Planning'] },
    { id:5, title:'Introduction to Stocks – Growing Your Business', duration:'8:42', videoId:'98qfFzqDKR8', done:false,
      desc:'How businesses grow by attracting investors — from small business to corporation.',
      concepts:['Business Growth','Investors','Equity','Scaling Up','Corporate Structure','Exit Strategy'] },
  ],
};
