/* ================================================================
   lessons.js  –  Grade 12 SHS
   All video IDs verified live from Khan Academy YouTube channel.
   Khan Academy videos are free, public, and allow embedding.
   ================================================================ */
const LESSONS = {

  /* ── CORE ── */

  'english-for-academic': [
    { id:1, title:'Introduction to Limits (Calculus basis for academic thinking)', duration:'11:32', videoId:'riXcZT2ICjA',
      desc:'Understand how to approach a value — a foundational thinking skill used in academic analysis and argumentation.',
      concepts:['Approaching a Value','Critical Analysis','Academic Reasoning','Logical Thinking'] },
    { id:2, title:'Derivative as a Concept (Rate of Change)', duration:'7:16', videoId:'N2PpRnFqnqY',
      desc:'Learn instantaneous rate of change — the core idea behind writing precise, evidence-based academic arguments.',
      concepts:['Rate of Change','Evidence-Based Writing','Precision','Argumentation'] },
    { id:3, title:'Mean, Median, and Mode', duration:'7:08', videoId:'h8EYEJ32oQ8',
      desc:'Statistical literacy for academic and professional writing — interpreting data in research papers and reports.',
      concepts:['Mean','Median','Mode','Data Interpretation','Research Skills'] },
    { id:4, title:'Sampling Methods and Research Design', duration:'8:30', videoId:'PdXDLNNXPik',
      desc:'How researchers select samples — critical for evaluating and writing evidence-based academic work.',
      concepts:['Random Sampling','Research Design','Bias','Survey Methods'] },
    { id:5, title:'Introduction to Interest (Financial Literacy)', duration:'9:05', videoId:'GtaoP0skPWc',
      desc:'Financial literacy for professional purposes — understanding interest rates in business and personal finance.',
      concepts:['Simple Interest','Compound Interest','Financial Literacy','Professional Skills'] },
  ],

  'practical-research-2': [
    { id:1, title:'Opportunity Cost and Scarcity', duration:'5:00', videoId:'pkEiHZAtoro',
      desc:'Research always involves trade-offs — understand opportunity cost as a framework for research decisions.',
      concepts:['Opportunity Cost','Research Trade-offs','Scarcity','Decision Making'] },
    { id:2, title:'Sampling Methods and Avoiding Bias', duration:'8:30', videoId:'PdXDLNNXPik',
      desc:'Learn probability and non-probability sampling methods and how to avoid bias in quantitative research.',
      concepts:['Random Sampling','Stratified Sampling','Sampling Bias','Survey Design'] },
    { id:3, title:'Mean, Median, Mode – Statistics for Research', duration:'7:08', videoId:'h8EYEJ32oQ8',
      desc:'Compute and interpret measures of central tendency for research data analysis.',
      concepts:['Mean','Median','Mode','Descriptive Statistics','Data Analysis'] },
    { id:4, title:'Introduction to Inflation – Interpreting Economic Data', duration:'6:11', videoId:'AaR1mPrdbTc',
      desc:'Understanding inflation data — practice interpreting and presenting quantitative findings.',
      concepts:['Inflation','Data Interpretation','Economic Indicators','Research Findings'] },
    { id:5, title:'Real vs Nominal GDP – Working with Research Data', duration:'9:49', videoId:'lBDT2w5Wl84',
      desc:'Understand real vs nominal values — essential for interpreting quantitative data in research papers.',
      concepts:['Real vs Nominal','GDP','Research Data','Quantitative Analysis'] },
  ],

  'filisopiya': [
    { id:1, title:'Mean, Median, Mode (Istatistika para sa Pananaliksik)', duration:'7:08', videoId:'h8EYEJ32oQ8',
      desc:'Pag-unawa sa istatistika bilang kasangkapan sa kritikal na pagsusuri ng impormasyon at datos.',
      concepts:['Istatistika','Kritikal na Pagsusuri','Pagbabasa ng Datos','Interpretasyon'] },
    { id:2, title:'Introduction to Limits – Kritikal na Pag-iisip', duration:'11:32', videoId:'riXcZT2ICjA',
      desc:'Ang konsepto ng limitasyon bilang modelo para sa kritikal na pagbabasa at pagsusuri ng teksto.',
      concepts:['Kritikal na Pag-iisip','Pagsusuri','Limitasyon ng Kaalaman','Argumento'] },
    { id:3, title:'Opportunity Cost – Pagpili at Pagsusuri', duration:'5:00', videoId:'pkEiHZAtoro',
      desc:'Paano gumagawa ng desisyon — isang modelo para sa pagsusuri ng mga pagpili sa anumang sitwasyon.',
      concepts:['Pagpili','Oportunidad','Pagsusuri ng Sitwasyon','Kritikal na Pag-iisip'] },
    { id:4, title:'Aggregate Demand – Ekonomiya at Lipunan', duration:'9:29', videoId:'oLhohwfwf_U',
      desc:'Pag-unawa sa kabuuang demand bilang panlipunang konsepto na may kaugnayan sa buhay ng mga Pilipino.',
      concepts:['Aggregate Demand','Ekonomiya','Lipunan','Panlipunang Konteksto'] },
    { id:5, title:'Introduction to Inflation – Pagbabasa ng Ekonomikong Teksto', duration:'6:11', videoId:'AaR1mPrdbTc',
      desc:'Pagbabasa at pagsusuri ng mga tekstong pangekonomiya — inflasyon at ang epekto nito sa buhay.',
      concepts:['Implasyon','Ekonomikong Teksto','Pagsusuri','Kontemporaneng Isyu'] },
  ],

  'understanding-culture': [
    { id:1, title:'Opportunity Cost – Economic Foundations of Society', duration:'5:00', videoId:'pkEiHZAtoro',
      desc:'How scarcity and trade-offs shape social and political decisions — a foundation of understanding society.',
      concepts:['Scarcity','Trade-offs','Social Decisions','Resource Allocation'] },
    { id:2, title:'Aggregate Demand – Society and the Economy', duration:'9:29', videoId:'oLhohwfwf_U',
      desc:'How collective economic behavior shapes society — government spending, consumption, and social welfare.',
      concepts:['Aggregate Demand','Government Spending','Consumption','Social Welfare'] },
    { id:3, title:'Introduction to Inflation – Social Impact', duration:'6:11', videoId:'AaR1mPrdbTc',
      desc:'How inflation affects different social classes — connecting economics to culture, society, and politics.',
      concepts:['Inflation','Social Inequality','Purchasing Power','Political Economy'] },
    { id:4, title:'Real vs Nominal GDP – Measuring Society', duration:'9:49', videoId:'lBDT2w5Wl84',
      desc:'GDP as a measure of societal progress — its uses and limitations in understanding culture and development.',
      concepts:['GDP','Human Development','Standard of Living','Economic Progress'] },
    { id:5, title:'Introduction to Interest – Power and Finance in Society', duration:'9:05', videoId:'GtaoP0skPWc',
      desc:'How interest and debt shape social power, inequality, and economic relationships between people.',
      concepts:['Interest','Debt','Economic Power','Social Inequality','Financial Systems'] },
  ],

  'media-info': [
    { id:1, title:'The Internet: IP Addresses and DNS', duration:'6:43', videoId:'MwxMsaFFycg',
      desc:'How the internet works — IP addresses, DNS, and the infrastructure that connects media and information.',
      concepts:['Internet','IP Addresses','DNS','Network Infrastructure','Digital Media'] },
    { id:2, title:'Cybersecurity and Online Crime', duration:'6:36', videoId:'5k24We8pED8',
      desc:'Understand cybersecurity threats, how hackers operate, and how to protect yourself online.',
      concepts:['Cybersecurity','Hacking','Online Safety','Malware','Digital Protection'] },
    { id:3, title:'Mean, Median, Mode – Reading Media Statistics', duration:'7:08', videoId:'h8EYEJ32oQ8',
      desc:'Statistical literacy for media consumers — how to critically evaluate numbers in news and media.',
      concepts:['Media Statistics','Data Literacy','Fact-Checking','Critical Consumption'] },
    { id:4, title:'Sampling Methods – How Media Polls Are Made', duration:'8:30', videoId:'PdXDLNNXPik',
      desc:'How surveys and polls are conducted — understanding sample bias in news reports and studies.',
      concepts:['Survey Methods','Sampling Bias','Media Polls','Information Credibility'] },
    { id:5, title:'Opportunity Cost – Choosing Your Media', duration:'5:00', videoId:'pkEiHZAtoro',
      desc:'Opportunity cost of media consumption — making informed choices about time spent on media platforms.',
      concepts:['Media Choices','Time Management','Opportunity Cost','Responsible Media Use'] },
  ],

  'pe-health-4': [
    { id:1, title:'Introduction to Work and Energy', duration:'10:05', videoId:'2WS1sG9fhOk',
      desc:'Physics of movement — how work and energy apply to physical activity, sports, and exercise science.',
      concepts:['Work','Energy','Physical Activity','Exercise Science','Calories'] },
    { id:2, title:'Conservation of Energy in Exercise', duration:'11:24', videoId:'kw_4Loo1HR4',
      desc:'How the body conserves and converts energy during physical activity and sports performance.',
      concepts:['Energy Conservation','Metabolism','ATP','Physical Performance','Fitness'] },
    { id:3, title:'Newton\'s First Law – Body in Motion', duration:'9:12', videoId:'CQYELiTtUs8',
      desc:'Newton\'s first law applied to fitness — inertia, momentum, and maintaining an active lifestyle.',
      concepts:['Inertia','Momentum','Active Lifestyle','Exercise Habits','Health Maintenance'] },
    { id:4, title:'Introduction to Interest – Financial Wellness', duration:'9:05', videoId:'GtaoP0skPWc',
      desc:'Financial health is part of total wellness — understanding compound interest for future planning.',
      concepts:['Financial Wellness','Compound Interest','Future Planning','Holistic Health'] },
  ],

  /* ── STEM ── */

  'gen-bio-2': [
    { id:1, title:'Flow of Energy and Matter through Ecosystems', duration:'8:44', videoId:'TitrRpMUt0I',
      desc:'How energy flows through food chains and webs — producers, consumers, decomposers, and trophic levels.',
      concepts:['Food Web','Trophic Levels','Energy Flow','Producers & Consumers','Decomposers'] },
    { id:2, title:'Natural Selection and the Owl Butterfly', duration:'10:22', videoId:'dR_BFmDMRaI',
      desc:'How natural selection drives adaptation and evolution through the butterfly camouflage example.',
      concepts:['Natural Selection','Adaptation','Camouflage','Variation','Fitness'] },
    { id:3, title:'Mitosis and Cell Division', duration:'12:44', videoId:'TKGcfbyFXsw',
      desc:'The stages of mitosis — how cells divide, replicate DNA, and produce identical daughter cells.',
      concepts:['Mitosis','Cell Cycle','DNA Replication','Prophase','Metaphase','Anaphase','Telophase'] },
    { id:4, title:'Introduction to Work and Energy (Biology Applications)', duration:'10:05', videoId:'2WS1sG9fhOk',
      desc:'Energy transformations in living systems — ATP, cellular respiration, and metabolic processes.',
      concepts:['ATP','Cellular Respiration','Energy Transformation','Metabolism','Bioenergetics'] },
    { id:5, title:'Conservation of Energy in Living Systems', duration:'11:24', videoId:'kw_4Loo1HR4',
      desc:'How organisms conserve energy — metabolic efficiency, photosynthesis, and respiration cycles.',
      concepts:['Energy Conservation','Photosynthesis','Respiration','Metabolic Efficiency'] },
  ],

  'gen-chem-2': [
    { id:1, title:'Reversible Reactions and Chemical Equilibrium', duration:'7:32', videoId:'i_LCF8gmcWQ',
      desc:'Introduction to reversible reactions and how systems reach dynamic chemical equilibrium.',
      concepts:['Reversible Reactions','Chemical Equilibrium','Dynamic Equilibrium','Forward & Reverse Reactions'] },
    { id:2, title:'Arrhenius Definition of Acids and Bases', duration:'8:30', videoId:'Y4HzGldIAss',
      desc:'The Arrhenius model of acids and bases — how they produce H⁺ and OH⁻ ions in water.',
      concepts:['Arrhenius Acids','Arrhenius Bases','H⁺ Ions','OH⁻ Ions','Aqueous Solutions'] },
    { id:3, title:'Introduction to Interest (Applied to Reaction Rates)', duration:'9:05', videoId:'GtaoP0skPWc',
      desc:'Exponential growth models in chemistry — how compound rates apply to reaction kinetics.',
      concepts:['Reaction Rates','Exponential Growth','Rate Constant','Chemical Kinetics'] },
    { id:4, title:'Mean, Median, Mode – Chemistry Data Analysis', duration:'7:08', videoId:'h8EYEJ32oQ8',
      desc:'Statistical analysis of experimental chemistry data — interpreting results from multiple trials.',
      concepts:['Data Analysis','Experimental Error','Statistics','Trials','Accuracy vs Precision'] },
    { id:5, title:'Conservation of Energy – Thermochemistry', duration:'11:24', videoId:'kw_4Loo1HR4',
      desc:'Law of conservation of energy applied to chemical reactions — endothermic and exothermic processes.',
      concepts:['Conservation of Energy','Enthalpy','Exothermic','Endothermic','Thermochemistry'] },
  ],

  'basic-calculus': [
    { id:1, title:'Introduction to Limits', duration:'11:32', videoId:'riXcZT2ICjA',
      desc:'What a limit is — understanding what a function approaches as the input gets closer to a value.',
      concepts:['Limit Definition','Approaching a Value','One-sided Limits','Undefined Points'] },
    { id:2, title:'Derivative as a Concept', duration:'7:16', videoId:'N2PpRnFqnqY',
      desc:'The derivative as instantaneous rate of change and slope of the tangent line.',
      concepts:['Derivative','Instantaneous Rate of Change','Tangent Line','Leibniz Notation','Lagrange Notation'] },
    { id:3, title:'Introduction to Related Rates', duration:'6:29', videoId:'kQF9pOqmS0U',
      desc:'How derivatives apply to related rates problems — finding how fast one quantity changes relative to another.',
      concepts:['Related Rates','Chain Rule','Implicit Differentiation','Real-World Applications'] },
    { id:4, title:'Antiderivatives and Indefinite Integrals', duration:'9:08', videoId:'MMv-027KEqU',
      desc:'Introduction to antiderivatives — reversing differentiation and writing indefinite integrals.',
      concepts:['Antiderivative','Indefinite Integral','Integration Rules','Constant of Integration'] },
    { id:5, title:'Conservation of Energy – Calculus Applied to Physics', duration:'11:24', videoId:'kw_4Loo1HR4',
      desc:'Calculus in action — using integrals and derivatives to model energy conservation in physical systems.',
      concepts:['Calculus Applications','Energy Models','Integral Calculus','Optimization','Physics'] },
  ],

  'gen-physics-1': [
    { id:1, title:'Introduction to Vectors and Scalars', duration:'9:38', videoId:'ihNZlp7iUHE',
      desc:'The difference between vector and scalar quantities — the foundation of all physics problem-solving.',
      concepts:['Vectors','Scalars','Magnitude','Direction','Displacement vs Distance'] },
    { id:2, title:'Average Velocity and Acceleration', duration:'9:00', videoId:'MAS6mBRZZXA',
      desc:'Kinematics fundamentals — computing average velocity, acceleration, and motion equations.',
      concepts:['Average Velocity','Acceleration','Kinematic Equations','Constant Acceleration','Displacement'] },
    { id:3, title:'Newton\'s First Law of Motion', duration:'9:12', videoId:'CQYELiTtUs8',
      desc:'Inertia and the first law — objects at rest and in motion, net force, and equilibrium.',
      concepts:['Inertia','Net Force','Equilibrium','Mass','Newton\'s First Law'] },
    { id:4, title:'Introduction to Work and Energy', duration:'10:05', videoId:'2WS1sG9fhOk',
      desc:'Work done by a force, kinetic and potential energy, and the work-energy theorem.',
      concepts:['Work','Kinetic Energy','Potential Energy','Work-Energy Theorem','Joules'] },
    { id:5, title:'Conservation of Energy', duration:'11:24', videoId:'kw_4Loo1HR4',
      desc:'Conservation of mechanical energy — how kinetic and potential energy transform into each other.',
      concepts:['Conservation of Energy','Mechanical Energy','Kinetic Energy','Potential Energy','Isolated Systems'] },
  ],

  'research-sci': [
    { id:1, title:'Sampling Methods and Avoiding Bias', duration:'8:30', videoId:'PdXDLNNXPik',
      desc:'Scientific sampling — random, stratified, and convenience sampling for research and experiments.',
      concepts:['Scientific Method','Sampling','Bias','Experimental Design','Variables'] },
    { id:2, title:'Mean, Median, Mode – Analyzing Scientific Data', duration:'7:08', videoId:'h8EYEJ32oQ8',
      desc:'Compute descriptive statistics to analyze and present scientific experimental data.',
      concepts:['Descriptive Statistics','Data Analysis','Mean','Median','Mode','Standard Deviation'] },
    { id:3, title:'Newton\'s First Law – Variables in Motion', duration:'9:12', videoId:'CQYELiTtUs8',
      desc:'How controlled experiments test Newton\'s laws — independent, dependent, and controlled variables.',
      concepts:['Independent Variable','Dependent Variable','Controlled Variable','Hypothesis','Scientific Method'] },
    { id:4, title:'Introduction to Work and Energy – Lab Applications', duration:'10:05', videoId:'2WS1sG9fhOk',
      desc:'Designing physics experiments — measuring work and energy, recording data, and interpreting results.',
      concepts:['Lab Report','Experimental Procedure','Data Collection','Results','Conclusion'] },
  ],

  /* ── HUMSS ── */

  'creative-writing': [
    { id:1, title:'Derivative as a Concept – The Art of Change', duration:'7:16', videoId:'N2PpRnFqnqY',
      desc:'How the concept of change and rate of change parallels character development and story transformation in creative writing.',
      concepts:['Character Arc','Transformation','Dynamic Characters','Story Change','Writer\'s Craft'] },
    { id:2, title:'Introduction to Limits – Approaching Your Story', duration:'11:32', videoId:'riXcZT2ICjA',
      desc:'Like limits, great stories approach a truth without fully stating it — subtlety and implication in creative writing.',
      concepts:['Show Don\'t Tell','Implication','Subtext','Narrative Tension','Writer\'s Voice'] },
    { id:3, title:'Opportunity Cost – Choosing Your Story', duration:'5:00', videoId:'pkEiHZAtoro',
      desc:'Every creative writing decision is an opportunity cost — choosing what to include, exclude, and emphasize.',
      concepts:['Creative Choices','Editing Decisions','Story Focus','Perspective','Genre Selection'] },
    { id:4, title:'Mean, Median, Mode – Story Structure Patterns', duration:'7:08', videoId:'h8EYEJ32oQ8',
      desc:'Analyzing patterns in literature — pacing, word frequency, and structural patterns in published works.',
      concepts:['Story Structure','Pacing','Literary Analysis','Pattern Recognition','Revision'] },
    { id:5, title:'The Internet: How Digital Stories Spread', duration:'6:43', videoId:'MwxMsaFFycg',
      desc:'How the internet distributes creative work — blogging, online publishing, and digital storytelling platforms.',
      concepts:['Digital Publishing','Online Platforms','Content Creation','Audience Reach','Social Media Writing'] },
  ],

  'community-engagement': [
    { id:1, title:'Opportunity Cost – Choosing to Serve', duration:'5:00', videoId:'pkEiHZAtoro',
      desc:'Volunteerism and community service involve opportunity costs — understanding what we give up to serve others.',
      concepts:['Volunteerism','Service','Opportunity Cost','Social Responsibility','Community'] },
    { id:2, title:'Aggregate Demand – Community Economics', duration:'9:29', videoId:'oLhohwfwf_U',
      desc:'How community spending and investment drive local economic development and social welfare.',
      concepts:['Community Development','Local Economy','Government Spending','Social Investment'] },
    { id:3, title:'Introduction to Inflation – Impact on Communities', duration:'6:11', videoId:'AaR1mPrdbTc',
      desc:'How inflation affects poor and marginalized communities — the social justice dimension of economic policy.',
      concepts:['Inflation','Poverty','Social Justice','Community Impact','Economic Policy'] },
    { id:4, title:'Cybersecurity – Protecting Community Online', duration:'6:36', videoId:'5k24We8pED8',
      desc:'How communities organize against online threats — digital citizenship and collective online safety.',
      concepts:['Digital Citizenship','Online Safety','Community Organizing','Advocacy','Cybercrime'] },
  ],

  'trends-networks': [
    { id:1, title:'The Internet: IP Addresses and DNS', duration:'6:43', videoId:'MwxMsaFFycg',
      desc:'How the internet infrastructure works — the network of networks that defines our digital society.',
      concepts:['Internet','Networks','IP Addresses','DNS','Global Connectivity'] },
    { id:2, title:'Cybersecurity and Online Crime', duration:'6:36', videoId:'5k24We8pED8',
      desc:'Cybersecurity threats in a networked world — how crime, hacking, and digital attacks shape society.',
      concepts:['Cybersecurity','Digital Crime','Social Engineering','Network Vulnerabilities','Online Safety'] },
    { id:3, title:'Aggregate Demand – Global Economic Trends', duration:'9:29', videoId:'oLhohwfwf_U',
      desc:'How global demand trends shape economies — understanding macroeconomic forces driving globalization.',
      concepts:['Globalization','Aggregate Demand','Economic Trends','Trade','Global Markets'] },
    { id:4, title:'Introduction to Inflation – 21st Century Economics', duration:'6:11', videoId:'AaR1mPrdbTc',
      desc:'Inflation as a global trend — how rising prices affect digital economies and modern societies.',
      concepts:['Inflation Trends','Digital Economy','Global Prices','Economic Inequality','Modern Society'] },
    { id:5, title:'Real vs Nominal GDP – Measuring Progress', duration:'9:49', videoId:'lBDT2w5Wl84',
      desc:'How we measure national progress — GDP, its limitations, and alternative measures of human development.',
      concepts:['GDP','Human Development','Economic Progress','National Income','Sustainable Development'] },
  ],

  'philliterature': [
    { id:1, title:'Opportunity Cost – Political Decision Making', duration:'5:00', videoId:'pkEiHZAtoro',
      desc:'How governments make policy decisions involving trade-offs — opportunity cost in governance and legislation.',
      concepts:['Government Policy','Trade-offs','Legislation','Political Decisions','Public Spending'] },
    { id:2, title:'Aggregate Demand – Government and the Economy', duration:'9:29', videoId:'oLhohwfwf_U',
      desc:'Fiscal policy — how the Philippine government uses spending and taxation to manage the economy.',
      concepts:['Fiscal Policy','Government Spending','Taxation','Philippine Economy','Governance'] },
    { id:3, title:'Introduction to Inflation – Philippine Economic Policy', duration:'6:11', videoId:'AaR1mPrdbTc',
      desc:'Inflation and the Bangko Sentral ng Pilipinas — monetary policy and its political implications.',
      concepts:['BSP','Monetary Policy','Inflation Control','Philippine Government','Economic Stability'] },
    { id:4, title:'Real vs Nominal GDP – Philippine Development', duration:'9:49', videoId:'lBDT2w5Wl84',
      desc:'Measuring Philippine economic progress — GDP, poverty, and the politics of development statistics.',
      concepts:['Philippine GDP','Development','Poverty Statistics','Economic Policy','Governance Accountability'] },
    { id:5, title:'Cybersecurity – Digital Governance', duration:'6:36', videoId:'5k24We8pED8',
      desc:'Cybercrime law and digital governance — the Philippine government\'s role in regulating cyberspace.',
      concepts:['RA 10175','Cybercrime Prevention','Digital Rights','Government Regulation','Online Freedom'] },
  ],

  /* ── ABM ── */

  'fundamentals-accountancy': [
    { id:1, title:'Introduction to Interest – Time Value of Money', duration:'9:05', videoId:'GtaoP0skPWc',
      desc:'The time value of money — why a peso today is worth more than a peso tomorrow. Foundation of accounting.',
      concepts:['Time Value of Money','Simple Interest','Compound Interest','Present Value','Future Value'] },
    { id:2, title:'Introduction to Stocks', duration:'8:42', videoId:'98qfFzqDKR8',
      desc:'What stocks are, how they represent ownership, and how they appear on the balance sheet.',
      concepts:['Stocks','Equity','Shareholders','Balance Sheet','Capital'] },
    { id:3, title:'Real vs Nominal GDP – Adjusting Financial Statements', duration:'9:49', videoId:'lBDT2w5Wl84',
      desc:'How inflation affects financial statements — adjusting for price changes in accounting and reporting.',
      concepts:['Inflation Adjustment','Financial Statements','Real vs Nominal Values','Accounting'] },
    { id:4, title:'Aggregate Demand – Macroeconomics for Accountants', duration:'9:29', videoId:'oLhohwfwf_U',
      desc:'How macroeconomic conditions affect business accounting — revenue, demand, and financial planning.',
      concepts:['Macroeconomics','Business Accounting','Revenue Forecasting','Financial Planning'] },
    { id:5, title:'Mean, Median, Mode – Financial Data Analysis', duration:'7:08', videoId:'h8EYEJ32oQ8',
      desc:'Statistical analysis of financial data — computing averages for budgeting and financial reporting.',
      concepts:['Financial Statistics','Budgeting','Average Costs','Data Analysis','Reporting'] },
  ],

  'applied-economics': [
    { id:1, title:'Opportunity Cost and Scarcity', duration:'5:00', videoId:'pkEiHZAtoro',
      desc:'The fundamental economic problem — scarcity forces choices, and every choice has an opportunity cost.',
      concepts:['Scarcity','Opportunity Cost','Economic Decisions','Trade-offs','Production Possibilities'] },
    { id:2, title:'Aggregate Demand', duration:'9:29', videoId:'oLhohwfwf_U',
      desc:'What drives total demand in an economy — consumption, investment, government spending, and net exports.',
      concepts:['Aggregate Demand','Consumption','Investment','Government Spending','Net Exports'] },
    { id:3, title:'Introduction to Inflation', duration:'6:11', videoId:'AaR1mPrdbTc',
      desc:'What causes inflation, how it is measured, and its effects on businesses, consumers, and government.',
      concepts:['Inflation','CPI','Purchasing Power','Cost-Push','Demand-Pull','Monetary Policy'] },
    { id:4, title:'Real vs Nominal GDP', duration:'9:49', videoId:'lBDT2w5Wl84',
      desc:'How to measure true economic growth by adjusting GDP for inflation using the GDP deflator.',
      concepts:['Real GDP','Nominal GDP','GDP Deflator','Economic Growth','National Income'] },
    { id:5, title:'Introduction to Stocks – Capital Markets', duration:'8:42', videoId:'98qfFzqDKR8',
      desc:'How businesses raise capital through stock markets — equity financing and the Philippine Stock Exchange.',
      concepts:['Stock Market','Capital Raising','PSE','Equity Financing','Investors'] },
  ],

  'business-finance': [
    { id:1, title:'Introduction to Interest – Time Value of Money', duration:'9:05', videoId:'GtaoP0skPWc',
      desc:'Present value, future value, and compound interest — the core of business finance and investment.',
      concepts:['Simple Interest','Compound Interest','Present Value','Future Value','Annuity'] },
    { id:2, title:'Introduction to Stocks – Equity Financing', duration:'8:42', videoId:'98qfFzqDKR8',
      desc:'How companies raise equity capital through stock issuance — dividends, stock price, and market value.',
      concepts:['Stocks','Equity','Dividends','IPO','Stock Price','Market Capitalization'] },
    { id:3, title:'Aggregate Demand – Business Investment Decisions', duration:'9:29', videoId:'oLhohwfwf_U',
      desc:'How macroeconomic aggregate demand drives business investment, capital budgeting, and expansion decisions.',
      concepts:['Investment Decisions','Capital Budgeting','Business Cycle','Demand Forecasting','NPV'] },
    { id:4, title:'Introduction to Inflation – Financial Planning', duration:'6:11', videoId:'AaR1mPrdbTc',
      desc:'How inflation erodes returns — adjusting financial projections for inflation in business finance.',
      concepts:['Inflation Risk','Real Return','Nominal Return','Financial Projections','Hedging'] },
    { id:5, title:'Real vs Nominal GDP – Economic Context for Finance', duration:'9:49', videoId:'lBDT2w5Wl84',
      desc:'Using macroeconomic data for financial analysis — GDP trends and their impact on business performance.',
      concepts:['Economic Analysis','GDP Trends','Business Performance','Financial Forecasting'] },
  ],

  'marketing': [
    { id:1, title:'Opportunity Cost – Marketing Resource Allocation', duration:'5:00', videoId:'pkEiHZAtoro',
      desc:'Marketing budgets involve opportunity costs — allocating resources between channels and campaigns.',
      concepts:['Marketing Budget','Resource Allocation','Opportunity Cost','ROI','Channel Strategy'] },
    { id:2, title:'Aggregate Demand – Understanding Your Market', duration:'9:29', videoId:'oLhohwfwf_U',
      desc:'How aggregate consumer demand shapes market size, pricing strategy, and marketing opportunities.',
      concepts:['Market Demand','Consumer Behavior','Market Size','Pricing Strategy','Target Market'] },
    { id:3, title:'Introduction to Inflation – Pricing Strategy', duration:'6:11', videoId:'AaR1mPrdbTc',
      desc:'How inflation forces marketers to adjust pricing — cost-plus pricing, value pricing, and consumer response.',
      concepts:['Pricing Strategy','Cost-Plus Pricing','Value Pricing','Inflation Impact','Consumer Response'] },
    { id:4, title:'The Internet: IP and DNS – Digital Marketing Infrastructure', duration:'6:43', videoId:'MwxMsaFFycg',
      desc:'How the internet enables digital marketing — websites, DNS, IP, and the technology behind online ads.',
      concepts:['Digital Marketing','Website Infrastructure','SEO','Online Advertising','Analytics'] },
    { id:5, title:'Introduction to Stocks – Brand Value and Equity', duration:'8:42', videoId:'98qfFzqDKR8',
      desc:'Brand equity as financial value — how strong brands increase company stock value and market position.',
      concepts:['Brand Equity','Brand Value','Market Position','Brand Loyalty','Company Valuation'] },
  ],

  /* ── TVL / All Strands ── */

  'empowerment-tech': [
    { id:1, title:'The Internet: IP Addresses and DNS', duration:'6:43', videoId:'MwxMsaFFycg',
      desc:'How the internet works — IP addressing, DNS, packets, and the infrastructure of digital communication.',
      concepts:['Internet','IP Addresses','DNS','Packets','Network Infrastructure','Cloud Computing'] },
    { id:2, title:'Cybersecurity and Online Crime', duration:'6:36', videoId:'5k24We8pED8',
      desc:'Cybersecurity fundamentals — phishing, malware, password safety, and protecting yourself online.',
      concepts:['Cybersecurity','Phishing','Malware','Password Safety','Digital Citizenship','Privacy'] },
    { id:3, title:'Mean, Median, Mode – Data and Spreadsheets', duration:'7:08', videoId:'h8EYEJ32oQ8',
      desc:'Using statistics and spreadsheets for data management — applying formulas in Google Sheets and Excel.',
      concepts:['Spreadsheets','Formulas','Data Analysis','Google Sheets','Excel','Statistical Functions'] },
    { id:4, title:'Sampling Methods – Digital Research Skills', duration:'8:30', videoId:'PdXDLNNXPik',
      desc:'Research skills in the digital age — conducting online surveys, collecting data, and avoiding bias.',
      concepts:['Online Research','Survey Tools','Sampling','Digital Literacy','Data Collection'] },
    { id:5, title:'Opportunity Cost – Digital Career Choices', duration:'5:00', videoId:'pkEiHZAtoro',
      desc:'Career planning in the digital economy — opportunity costs of different ICT career paths.',
      concepts:['Digital Careers','ICT Career Paths','Opportunity Cost','Skills Development','Tech Jobs'] },
  ],

  'entrep': [
    { id:1, title:'Opportunity Cost – The Entrepreneurial Choice', duration:'5:00', videoId:'pkEiHZAtoro',
      desc:'Starting a business involves opportunity costs — leaving employment, investing savings, and taking risks.',
      concepts:['Entrepreneurial Risk','Opportunity Cost','Business Decision','Capital Investment','Risk-Taking'] },
    { id:2, title:'Aggregate Demand – Reading Your Market', duration:'9:29', videoId:'oLhohwfwf_U',
      desc:'Understanding market demand before launching a business — consumer spending patterns and market timing.',
      concepts:['Market Analysis','Consumer Demand','Market Timing','Business Opportunity','Feasibility'] },
    { id:3, title:'Introduction to Interest – Business Financing', duration:'9:05', videoId:'GtaoP0skPWc',
      desc:'How loans and interest work for small business financing — computing the true cost of borrowing.',
      concepts:['Business Loans','Interest Rate','Loan Repayment','Financing Costs','Break-even'] },
    { id:4, title:'Introduction to Inflation – Business Pricing', duration:'6:11', videoId:'AaR1mPrdbTc',
      desc:'How inflation affects small business pricing, costs, and profit margins — adjusting your business plan.',
      concepts:['Pricing','Inflation Impact','Cost Management','Profit Margins','Business Planning'] },
    { id:5, title:'Introduction to Stocks – Growing Your Business', duration:'8:42', videoId:'98qfFzqDKR8',
      desc:'How businesses grow by attracting investors — from sari-sari store to corporation and beyond.',
      concepts:['Business Growth','Investors','Equity','Scaling Up','Corporate Structure','Exit Strategy'] },
  ],
};
